### ANÁLISE DA VIOLÊNCIA DE JUIZ DE FORA

In [53]:
import pandas as pd

In [133]:

# Exibir todas as colunas do DataFrame
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows',None)

In [105]:
df_roubo_veiculos = pd.read_csv(r'dados\veiculos.csv', sep = ',')

In [98]:
df_roubo_veiculos.reset_index()

,index,Unnamed: 0,Número REDS,Qtde Veículos,Natureza Principal Completa,Ano Fato,Mês Fato Resumido,Mês Numérico Fato,Data Fato,Dia da Semana Fato,Horário Fato,Faixa 1 Hora Fato,Faixa 6 Horas Fato,Tipo Veículo,Alvo Corrigido,Situação Veículo,Causa Presumida,Descrição Meio Utilizado,Descrição Grupo Local Imediato,Descrição Local Imediato,Logradouro Ocorrência - Tipo,Bairro,Bairro Não Cadastrado,Bairro - FATO FINAL,Bairro - FATO FINAL - Municipio,Município,Município - Código,UF - Sigla,RISP,RMBH
0,0,93,2015-000079420-001,1.0,FURTO CONSUMADO,2015.0,JAN,1.0,02/01/2015,SEXTA-FEIRA,00:30:00,De 00:00 as 00:59,De 00:00 as 05:59,AUTOMOVEL,Veículos,FURTADO,OUTRAS MOTIVACOES/CAUSAS,OUTROS MEIOS (DESCREVER EM CAMPO ESPECIFICO),VIA DE ACESSO,VIA DE ACESSO PUBLICA,RUA,FRANCISCO BERNARDINO,NaN,FRANCISCO BERNARDINO,"FRANCISCO BERNARDINO, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
1,1,132,2015-000119317-001,1.0,FURTO CONSUMADO,2015.0,JAN,1.0,02/01/2015,SEXTA-FEIRA,20:30:00,De 20:00 as 20:59,De 18:00 as 23:59,MOTOCICLETA,Veículos,FURTADO,VANTAGEM ECONOMICA,CONHECIMENTO TECNICO ESPECIFICO,VIA DE ACESSO,VIA DE ACESSO PUBLICA,RUA,CIDADE DO SOL,NaN,CIDADE DO SOL,"CIDADE DO SOL, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
2,2,238,2015-000198015-001,1.0,FURTO CONSUMADO,2015.0,JAN,1.0,04/01/2015,DOMINGO,10:00:00,De 10:00 as 10:59,De 06:00 as 11:59,AUTOMOVEL,Veículos,FURTADO,IGNORADO,MEIO DESCONHECIDO,VIA DE ACESSO,VIA DE ACESSO PUBLICA,AVENIDA,ALTO DOS PASSOS,NaN,ALTO DOS PASSOS,"ALTO DOS PASSOS, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
3,3,256,2015-000218977-001,1.0,FURTO CONSUMADO,2015.0,JAN,1.0,04/01/2015,DOMINGO,16:00:00,De 16:00 as 16:59,De 12:00 as 17:59,MOTOCICLETA,Veículos,FURTADO,VANTAGEM ECONOMICA,ARROMBAMENTO/ROMPIMENTO DE OBSTACULO,RESIDENCIA UNIFAMILIAR URBANA,CASA,RUA,QUINTA DAS AVENIDAS,QUINTA DAS AVENIDAS,QUINTA DAS AVENIDAS,"QUINTA DAS AVENIDAS, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
4,4,270,2015-000237512-001,1.0,FURTO CONSUMADO,2015.0,JAN,1.0,04/01/2015,DOMINGO,22:30:00,De 22:00 as 22:59,De 18:00 as 23:59,AUTOMOVEL,Veículos,FURTADO,VANTAGEM ECONOMICA,MEIO DESCONHECIDO,VIA DE ACESSO,VIA DE ACESSO PUBLICA,RUA,GRAJAU,NaN,GRAJAU,"GRAJAU, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5486,5486,1028955,2024-053293996-001,1.0,ROUBO CONSUMADO,2024.0,NOV,11.0,28/11/2024,QUINTA-FEIRA,01:26:52,De 01:00 as 01:59,De 00:00 as 05:59,AUTOMOVEL,Veículos,ROUBADO,VANTAGEM ECONOMICA,SIMULACRO DE ARMA DE FOGO,VIA DE ACESSO,VIA DE ACESSO PUBLICA,RUA,GRANBERY,NaN,GRANBERY,"GRANBERY, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
5487,5487,1029204,2024-056289281-001,1.0,ROUBO CONSUMADO,2024.0,DEZ,12.0,16/12/2024,SEGUNDA-FEIRA,19:30:00,De 19:00 as 19:59,De 18:00 as 23:59,AUTOMOVEL,Veículos,ROUBADO,VANTAGEM ECONOMICA,ARMAS DE FOGO,RESIDENCIA UNIFAMILIAR URBANA,CASA,AVENIDA,SALVATERRA,NaN,SALVATERRA,"SALVATERRA, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
5488,5488,1029399,2024-058291216-001,1.0,ROUBO CONSUMADO,2024.0,DEZ,12.0,30/12/2024,SEGUNDA-FEIRA,21:21:13,De 21:00 as 21:59,De 18:00 as 23:59,MOTOCICLETA,Veículos,ROUBADO,VANTAGEM ECONOMICA,ARMAS DE FOGO,VIA DE ACESSO,VIA DE ACESSO PUBLICA,RUA,SAO MATEUS,NaN,SAO MATEUS,"SAO MATEUS, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
5489,5489,1029491,2025-000993067-001,1.0,ROUBO CONSUMADO,2025.0,JAN,1.0,07/01/2025,TERÇA-FEIRA,23:30:00,De 23:00 as 23:59,De 18:00 as 23:59,AUTOMOVEL,Veículos,ROUBADO,VANTAGEM ECONOMICA,ARMAS DE FOGO,VIA DE ACESSO,VIA DE ACESSO PUBLICA,RUA,VALE DO AMANHECER,NaN,VALE DO AMANHECER,"VALE DO AMANHECER, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
5490,5490,1029549,2025-001775464-001,1.0,ROUBO CONSUMADO,2025.0,JAN,1.0,12/01/2025,DOMINGO,19:14:05,De 19:00 as 19:59,De 18:00 as 23:59,MOTOCICLETA,Veículos,ROUBADO,VANTAGEM ECONOMICA,ARMAS DE FOGO,VIA DE ACESSO,VIA DE ACESSO PUBLICA,RUA,SANTA HELENA,NaN,SANTA HELENA,"SANTA HELENA, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG

In [106]:
df_roubo_veiculos.columns

Index(['Unnamed: 0', 'Número REDS', 'Qtde Veículos',
       'Natureza Principal Completa', 'Ano Fato', 'Mês Fato Resumido',
       'Mês Numérico Fato', 'Data Fato', 'Dia da Semana Fato', 'Horário Fato',
       'Faixa 1 Hora Fato', 'Faixa 6 Horas Fato', 'Tipo Veículo',
       'Alvo Corrigido', 'Situação Veículo', 'Causa Presumida',
       'Descrição Meio Utilizado', 'Descrição Grupo Local Imediato',
       'Descrição Local Imediato', 'Logradouro Ocorrência - Tipo', 'Bairro',
       'Bairro Não Cadastrado', 'Bairro - FATO FINAL',
       'Bairro - FATO FINAL - Municipio ', 'Município', 'Município - Código',
       'UF - Sigla', 'RISP ', 'RMBH'],
      dtype='object')

In [107]:
df_roubo_veiculos = df_roubo_veiculos.drop(columns=['Unnamed: 0', 'Número REDS', 'Ano Fato', 'Mês Fato Resumido','Mês Numérico Fato',
                                                    'Faixa 1 Hora Fato', 'Faixa 6 Horas Fato', 'Alvo Corrigido', 'Situação Veículo', 
                                                    'Descrição Grupo Local Imediato','Logradouro Ocorrência - Tipo', 
                                                    'Bairro Não Cadastrado', 'Bairro - FATO FINAL','Bairro - FATO FINAL - Municipio ',
                                                    'Município', 'Município - Código','UF - Sigla', 'RISP ', 'RMBH'], axis=1)

In [108]:
df_roubo_veiculos.columns

Index(['Qtde Veículos', 'Natureza Principal Completa', 'Data Fato',
       'Dia da Semana Fato', 'Horário Fato', 'Tipo Veículo', 'Causa Presumida',
       'Descrição Meio Utilizado', 'Descrição Local Imediato', 'Bairro'],
      dtype='object')

In [109]:
df_roubo_veiculos

,Qtde Veículos,Natureza Principal Completa,Data Fato,Dia da Semana Fato,Horário Fato,Tipo Veículo,Causa Presumida,Descrição Meio Utilizado,Descrição Local Imediato,Bairro
0,1.0,FURTO CONSUMADO,02/01/2015,SEXTA-FEIRA,00:30:00,AUTOMOVEL,OUTRAS MOTIVACOES/CAUSAS,OUTROS MEIOS (DESCREVER EM CAMPO ESPECIFICO),VIA DE ACESSO PUBLICA,FRANCISCO BERNARDINO
1,1.0,FURTO CONSUMADO,02/01/2015,SEXTA-FEIRA,20:30:00,MOTOCICLETA,VANTAGEM ECONOMICA,CONHECIMENTO TECNICO ESPECIFICO,VIA DE ACESSO PUBLICA,CIDADE DO SOL
2,1.0,FURTO CONSUMADO,04/01/2015,DOMINGO,10:00:00,AUTOMOVEL,IGNORADO,MEIO DESCONHECIDO,VIA DE ACESSO PUBLICA,ALTO DOS PASSOS
3,1.0,FURTO CONSUMADO,04/01/2015,DOMINGO,16:00:00,MOTOCICLETA,VANTAGEM ECONOMICA,ARROMBAMENTO/ROMPIMENTO DE OBSTACULO,CASA,QUINTA DAS AVENIDAS
4,1.0,FURTO CONSUMADO,04/01/2015,DOMINGO,22:30:00,AUTOMOVEL,VANTAGEM ECONOMICA,MEIO DESCONHECIDO,VIA DE ACESSO PUBLICA,GRAJAU
...,...,...,...,...,...,...,...,...,...,...
5486,1.0,ROUBO CONSUMADO,28/11/2024,QUINTA-FEIRA,01:26:52,AUTOMOVEL,VANTAGEM ECONOMICA,SIMULACRO DE ARMA DE FOGO,VIA DE ACESSO PUBLICA,GRANBERY
5487,1.0,ROUBO CONSUMADO,16/12/2024,SEGUNDA-FEIRA,19:30:00,AUTOMOVEL,VANTAGEM ECONOMICA,ARMAS DE FOGO,CASA,SALVATERRA
5488,1.0,ROUBO CONSUMADO,30/12/2024,SEGUNDA-FEIRA,21:21:13,MOTOCICLETA,VANTAGEM ECONOMICA,ARMAS DE FOGO,VIA DE ACESSO PUBLICA,SAO MATEUS
5489,1.0,ROUBO CONSUMADO,07/01/2025,TERÇA-FEIRA,23:30:00,AUTOMOVEL,VANTAGEM ECONOMICA,ARMAS DE FOGO,VIA DE ACESSO PUBLICA,VALE DO AMANHECER
5490,1.0,ROUBO CONSUMADO,12/01/2025,DOMINGO,19:14:05,MOTOCICLETA,VANTAGEM ECONOMICA,ARMAS DE FOGO,VIA DE ACESSO PUBLICA,SANTA HELENA

In [110]:
# verificando se existe valores nulos
df_roubo_veiculos.isnull().sum()

Qtde Veículos                  0
Natureza Principal Completa    0
Data Fato                      0
Dia da Semana Fato             0
Horário Fato                   0
Tipo Veículo                   0
Causa Presumida                0
Descrição Meio Utilizado       0
Descrição Local Imediato       0
Bairro                         0
dtype: int64

In [120]:
df_roubo_veiculos.columns

Index(['Qtde Veículos', 'Natureza Principal Completa', 'Data Fato',
       'Dia da Semana Fato', 'Horário Fato', 'Tipo Veículo', 'Causa Presumida',
       'Descrição Meio Utilizado', 'Descrição Local Imediato', 'Bairro'],
      dtype='object')

In [123]:
df_roubo_veiculos['Natureza Principal Completa'].unique()

array(['FURTO CONSUMADO', 'ROUBO CONSUMADO'], dtype=object)

In [136]:
df_roubo_veiculos.groupby(['Bairro']).value_counts()

Bairro                     Qtde Veículos  Natureza Principal Completa  Data Fato   Dia da Semana Fato  Horário Fato  Tipo Veículo                                   Causa Presumida                       Descrição Meio Utilizado                       Descrição Local Imediato
ADOLFO VIRECH              1.0            FURTO CONSUMADO              09/08/2022  TERÇA-FEIRA         15:34:37      REBOQUE                                        IGNORADO                              MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
AEROPORTO                  1.0            FURTO CONSUMADO              02/04/2016  SÁBADO              18:30:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    ARROMBAMENTO/ROMPIMENTO DE OBSTACULO           VIA DE ACESSO PUBLICA                            2
                                                                       01/08/2023  TERÇA-FEIRA         00:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       03/09/2023  DOMINGO             05:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    EMPREGO DE CHAVE FALSA / MICHA / GAZUA         VIA DE ACESSO PUBLICA                            1
                                                                       04/05/2016  QUARTA-FEIRA        12:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       05/02/2017  DOMINGO             22:09:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       05/11/2023  DOMINGO             11:11:01      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       06/12/2016  TERÇA-FEIRA         09:00:00      AUTOMOVEL                                      IGNORADO                              OUTROS MEIOS (DESCREVER EM CAMPO ESPECIFICO)   VIA DE ACESSO PUBLICA                            1
                                                                       07/04/2015  TERÇA-FEIRA         22:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       09/02/2016  TERÇA-FEIRA         21:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       10/07/2022  DOMINGO             08:59:26      MOTOCICLETA                                    IGNORADO                              MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       11/06/2022  SÁBADO              05:49:25      MOTOCICLETA                                    VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       12/10/2017  QUINTA-FEIRA        05:07:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       13/01/2018  SÁBADO              07:02:00      MOTOCICLETA                                    VANTAGEM ECONOMICA                    ARROMBAMENTO/ROMPIMENTO DE OBSTACULO           EDIFICIO RESIDENCIAL                             1
                                                                       13/03/2017  SEGUNDA-FEIRA       23:52:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              HOSPITAL                                         1
                                                                       14/03/2023  TERÇA-FEIRA         09:22:14      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       14/04/2017  SEXTA-FEIRA         04:56:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       14/09/2015  SEGUNDA-FEIRA       05:25:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       14/10/2019  SEGUNDA-FEIRA       20:23:30      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       18/08/2015  TERÇA-FEIRA         16:00:00      MOTOCICLETA                                    VANTAGEM ECONOMICA                    ABUSO DE CONFIANCA                             CASA                                             1
                                                                       18/12/2016  DOMINGO             07:31:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       20/09/2019  SEXTA-FEIRA         10:14:21      AUTOMOVEL                                      VANTAGEM ECONOMICA                    CONHECIMENTO TECNICO ESPECIFICO                VIA DE ACESSO PUBLICA                            1
                                                                       21/12/2023  QUINTA-FEIRA        19:30:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    OUTROS MEIOS (DESCREVER EM CAMPO ESPECIFICO)   VIA DE ACESSO PUBLICA                            1
                                                                       23/09/2019  SEGUNDA-FEIRA       17:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       24/10/2019  QUINTA-FEIRA        01:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       25/09/2022  DOMINGO             12:21:37      MOTOCICLETA                                    VANTAGEM ECONOMICA                    EMPREGO DE CHAVE FALSA / MICHA / GAZUA         VIA DE ACESSO PUBLICA                            1
                                                                       26/03/2023  DOMINGO             04:00:00      MOTOCICLETA                                    IGNORADO                              EMPREGO DE CHAVE FALSA / MICHA / GAZUA         BOATE / CASA DE SHOW / SIMILAR                   1
                                                                       26/05/2024  DOMINGO             03:07:06      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       26/11/2022  SÁBADO              08:26:53      MOTOCICLETA                                    IGNORADO                              MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       27/04/2019  SÁBADO              15:00:00      MOTOCICLETA                                    VANTAGEM ECONOMICA                    OUTROS MEIOS (DESCREVER EM CAMPO ESPECIFICO)   VIA DE ACESSO PUBLICA                            1
                                                                       28/01/2022  SEXTA-FEIRA         09:58:21      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       30/08/2022  TERÇA-FEIRA         07:32:38      AUTOMOVEL                                      VANTAGEM ECONOMICA                    OUTROS MEIOS (DESCREVER EM CAMPO ESPECIFICO)   CASA                                             1
                                          ROUBO CONSUMADO              02/04/2023  DOMINGO             04:25:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    ARMAS DE FOGO                                  VIA DE ACESSO PUBLICA                            1
                                                                       04/05/2015  SEGUNDA-FEIRA       18:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    ARMAS DE FOGO                                  OUTROS - ESTABELECIMENTOS COMERCIAIS / SERVIC    1
                                                                       07/09/2021  TERÇA-FEIRA         18:45:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    ARMAS DE FOGO                                  VIA DE ACESSO PUBLICA                            1
                                                                       08/09/2017  SEXTA-FEIRA         22:29:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    ARMAS DE FOGO                                  VIA DE ACESSO PARTICULAR/PRIVADA                 1
                                                                       08/10/2023  DOMINGO             21:33:57      MOTOCICLETA                                    VANTAGEM ECONOMICA                    ARMAS DE FOGO                                  VIA DE ACESSO PUBLICA                            1
                                                                       14/02/2016  DOMINGO             05:45:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    ARMAS DE FOGO                                  VIA DE ACESSO PUBLICA                            1
                                                                       18/11/2015  QUARTA-FEIRA        15:45:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    ARMAS DE FOGO                                  OUTROS - ESTABELECIMENTOS COMERCIAIS / SERVIC    1
ALTO BAIRU                 1.0            FURTO CONSUMADO              06/05/2016  SEXTA-FEIRA         07:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    EMPREGO DE CHAVE FALSA / MICHA / GAZUA         VIA DE ACESSO PUBLICA                            1
                                                                       08/01/2017  DOMINGO             19:56:00      MOTOCICLETA                                    VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       22/01/2015  QUINTA-FEIRA        08:00:00      MOTOCICLETA                                    VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       30/07/2021  SEXTA-FEIRA         11:41:13      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
ALTO DOS PASSOS            1.0            FURTO CONSUMADO              01/06/2016  QUARTA-FEIRA        15:00:00      AUTOMOVEL                                      IGNORADO                              EMPREGO DE CHAVE FALSA / MICHA / GAZUA         AUTOMOVEL                                        1
                                                                       01/09/2019  DOMINGO             09:45:14      AUTOMOVEL                                      IGNORADO                              MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       02/07/2019  TERÇA-FEIRA         11:52:19      AUTOMOVEL                                      IGNORADO                              MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       02/09/2017  SÁBADO              22:33:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              MERCEARIA / SACOLAO / SUPERMERCADO               1
                                                                       03/03/2022  QUINTA-FEIRA        19:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       03/05/2022  TERÇA-FEIRA         06:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       03/06/2015  QUARTA-FEIRA        20:00:00      AUTOMOVEL                                      IGNORADO                              MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       03/12/2015  QUINTA-FEIRA        10:00:00      AUTOMOVEL                                      OUTRAS MOTIVACOES/CAUSAS              OUTROS MEIOS (DESCREVER EM CAMPO ESPECIFICO)   VIA DE ACESSO PUBLICA                            1
                                                                       04/01/2015  DOMINGO             10:00:00      AUTOMOVEL                                      IGNORADO                              MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       04/03/2016  SEXTA-FEIRA         20:00:00      CICLOMOTOR                                     IGNORADO                              MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       04/09/2016  DOMINGO             00:11:00      AUTOMOVEL                                      IGNORADO                              MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       05/02/2019  TERÇA-FEIRA         11:13:15      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       06/03/2016  DOMINGO             22:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       06/11/2019  QUARTA-FEIRA        07:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       07/10/2015  QUARTA-FEIRA        11:00:00      MOTOCICLETA                                    VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                                                       19:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              AUTOMOVEL                                        1
                                                                       07/10/2016  SEXTA-FEIRA         07:44:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    ARROMBAMENTO/ROMPIMENTO DE OBSTACULO           ESTACIONAMENTO / GARAGEM                         1
                                                                       07/11/2016  SEGUNDA-FEIRA       22:00:00      MOTOCICLETA                                    VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              VIA DE ACESSO PUBLICA                            1
                                                                       08/04/2015  QUARTA-FEIRA        10:00:00      AUTOMOVEL                                      VANTAGEM ECONOMICA                    MEIO DESCONHECIDO                              ESTACIONAMENTO / GARAGEM                         1
                                                                       09/02/2020  DOMINGO             17:17:56      MOTOCICLETA                                    IGNORADO                              ARROMBAMENTO/ROMPIMENTO DE OBSTACULO           ESTACIONAMENTO / GARAGEM                         1
                                                                       09/04/2018  SEGUNDA-FEIRA       11:06:25      MOTOCICLETA                                    VANTAGEM ECONOMICA                    ESCALADA                                       OUTROS - RESIDENCIAS URBANAS                     1
                                                                       09/08/2016  TERÇA-FEIRA         11:00:00      MOTOCICLETA                                    VANTAGEM ECONOMICA                    CONHECIMENTO TECNICO ESPECIFICO                VIA DE ACESSO PUBLICA                            1