## ANÁLISE DE CRIMES VIOLENTOS

In [ ]:
# importações
import pandas as pd

In [31]:
# importação dos dados
tabela = pd.read_csv(r'dados/crimes_violentos.csv')

In [8]:
tabela.shape

(20752, 26)

In [ ]:
# Amostra de dados
tabela.head()

,Unnamed: 0,Número REDS,Qtde Ocorrências,Natureza Principal Completa,Ano Fato,Mês Fato Resumido,Mês Numérico Fato,Data Fato,Dia da Semana Fato,Horário Fato,...,Logradouro Ocorrência - Tipo,Bairro,Bairro Não Cadastrado,Bairro - FATO FINAL,Bairro - FATO FINAL - Municipio,Município,Município - Código,UF - Sigla,RISP,RMBH
0,13,2012-000001066-001,1.0,ROUBO CONSUMADO,2012.0,JAN,1.0,01/01/2012,DOMINGO,03:05:00,...,AVENIDA,DISTRITO INDUSTRIAL,NaN,DISTRITO INDUSTRIAL,"DISTRITO INDUSTRIAL, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
1,117,2012-000013850-001,1.0,ROUBO CONSUMADO,2012.0,JAN,1.0,01/01/2012,DOMINGO,20:30:00,...,RUA,MUCUNGE DA GRAMA,NaN,MUCUNGE DA GRAMA,"MUCUNGE DA GRAMA, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
2,190,2012-000008207-001,1.0,ROUBO CONSUMADO,2012.0,JAN,1.0,02/01/2012,SEGUNDA-FEIRA,13:00:00,...,AVENIDA,SAO BENEDITO,NaN,SAO BENEDITO,"SAO BENEDITO, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
3,228,2012-000011492-001,1.0,ROUBO CONSUMADO,2012.0,JAN,1.0,02/01/2012,SEGUNDA-FEIRA,18:00:00,...,AVENIDA,MARIANO PROCOPIO,NaN,MARIANO PROCOPIO,"MARIANO PROCOPIO, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG
4,403,2012-000018063-001,1.0,ROUBO CONSUMADO,2012.0,JAN,1.0,03/01/2012,TERÇA-FEIRA,16:10:00,...,AVENIDA,CENTRO,NaN,CENTRO,"CENTRO, JUIZ DE FORA",JUIZ DE FORA,313670.0,MG,4.0,3) Interior de MG

In [13]:
# verificando se existem nulos
tabela.isnull().sum()

Unnamed: 0                             0
Número REDS                            0
Qtde Ocorrências                       0
Natureza Principal Completa            0
Ano Fato                               0
Mês Fato Resumido                      0
Mês Numérico Fato                      0
Data Fato                              0
Dia da Semana Fato                     0
Horário Fato                           0
Faixa 1 Hora Fato                      0
Faixa 6 Horas Fato                     0
Causa Presumida                        0
Desc Longa Meio Utilizado              0
Descrição Grupo Local Imediato         0
Descrição Local Imediato               0
Logradouro Ocorrência - Tipo           0
Bairro                                 0
Bairro Não Cadastrado              19136
Bairro - FATO FINAL                    0
Bairro - FATO FINAL - Municipio        0
Município                              0
Município - Código                     0
UF - Sigla                             0
RISP                                   0
RMBH                                   0
dtype: int64

In [14]:
tabela.columns

Index(['Unnamed: 0', 'Número REDS', 'Qtde Ocorrências',
       'Natureza Principal Completa', 'Ano Fato', 'Mês Fato Resumido',
       'Mês Numérico Fato', 'Data Fato', 'Dia da Semana Fato', 'Horário Fato',
       'Faixa 1 Hora Fato', 'Faixa 6 Horas Fato', 'Causa Presumida',
       'Desc Longa Meio Utilizado', 'Descrição Grupo Local Imediato',
       'Descrição Local Imediato', 'Logradouro Ocorrência - Tipo', 'Bairro',
       'Bairro Não Cadastrado', 'Bairro - FATO FINAL',
       'Bairro - FATO FINAL - Municipio', 'Município', 'Município - Código',
       'UF - Sigla', 'RISP ', 'RMBH'],
      dtype='object')

In [32]:
# excluindo as colunas Unnamed,	Número REDS,		Natureza Principal Completa	Ano Fato	Mês Fato Resumido	Mês Numérico Fato	Data Fato	Dia da Semana Fato	Horário Fato	...	Logradouro Ocorrência - Tipo	Bairro	Bairro Não Cadastrado	Bairro - FATO FINAL	Bairro - FATO FINAL - Municipio	Município	Município - Código	UF - Sigla	RISP	RMBH
tabela = tabela.drop(columns=['Unnamed: 0','Número REDS','Ano Fato','Mês Numérico Fato','Logradouro Ocorrência - Tipo','Faixa 6 Horas Fato','Descrição Grupo Local Imediato','Bairro','Bairro Não Cadastrado','Município','UF - Sigla','Município - Código','Bairro - FATO FINAL - Municipio','RISP ','RMBH'])
tabela.sample(5)

,Qtde Ocorrências,Natureza Principal Completa,Mês Fato Resumido,Data Fato,Dia da Semana Fato,Horário Fato,Faixa 1 Hora Fato,Causa Presumida,Desc Longa Meio Utilizado,Descrição Local Imediato,Bairro - FATO FINAL
13464,1.0,ROUBO TENTADO,OUT,05/10/2017,QUINTA-FEIRA,14:42:00,De 14:00 as 14:59,VANTAGEM ECONOMICA,AMEACA,VIA DE ACESSO PUBLICA,BOTANAGUA
2969,1.0,ROUBO CONSUMADO,AGO,06/08/2013,TERÇA-FEIRA,19:30:00,De 19:00 as 19:59,OUTRAS MOTIVACOES/CAUSAS,ARMAS DE FOGO,CONFEITARIA / PADARIA / PANIFICADORA,TEIXEIRAS
12975,1.0,HOMICIDIO CONSUMADO,JUL,01/07/2017,SÁBADO,17:55:00,De 17:00 as 17:59,IGNORADO,ARMAS DE FOGO,CASA,NOVO TRIUNFO
15250,1.0,ROUBO CONSUMADO,NOV,04/11/2018,DOMINGO,20:45:10,De 20:00 as 20:59,VANTAGEM ECONOMICA,SIMULACRO DE ARMA DE FOGO,CASA,LINHARES
3729,1.0,EXTORSAO TENTADO,DEZ,12/12/2013,QUINTA-FEIRA,11:44:00,De 11:00 as 11:59,OUTRAS MOTIVACOES/CAUSAS,OUTROS MEIOS (DESCREVER EM CAMPO ESPECIFICO),VIA DE ACESSO PUBLICA,JARDIM NATAL

In [50]:
tabela.columns

Index(['Qtde Ocorrências', 'Natureza Principal Completa', 'Mês Fato Resumido',
       'Data Fato', 'Dia da Semana Fato', 'Horário Fato', 'Faixa 1 Hora Fato',
       'Causa Presumida', 'Desc Longa Meio Utilizado',
       'Descrição Local Imediato', 'Bairro - FATO FINAL'],
      dtype='object')

In [58]:
tabela.rename(columns={'Qtde Ocorrências':'numero_ocorrencias', 'Natureza Principal Completa':'crime',
       'Mês Fato Resumido':'mes',  'Data Fato':'data','Dia da Semana Fato':'dia_semana', 'Horário Fato':'horario',
       'Faixa 1 Hora Fato':'faixa_horaria_crime','Causa Presumida':'causa', 'Desc Longa Meio Utilizado':'meio_utilizado',
        'Descrição Local Imediato':'local', 'Bairro - FATO FINAL':'bairro'},inplace=True)

In [59]:
tabela.columns

Index(['numero_ocorrencias', 'crime', 'mes', 'data', 'dia_semana', 'horario',
       'faixa_horaria_crime', 'causa', 'meio_utilizado', 'local', 'bairro'],
      dtype='object')

In [62]:
# Convertendo colunas numéricas para o tipo inteiro
tabela['numero_ocorrencias'] = tabela['numero_ocorrencias'].astype(int)
tabela['data'] = tabela['data'].astype('datetime64[ns]')

In [ ]:
# criando a coluna ano 
tabela['ano'] = tabela['data'].dt.year

In [ ]:
# criando a coluna hora ocorrido 
tabela['hora_ocorrido'] = tabela['horario'].apply(lambda x: x.strip().split(':')[0])

In [78]:
tabela.head()

,numero_ocorrencias,crime,mes,data,dia_semana,horario,faixa_horaria_crime,causa,meio_utilizado,local,bairro,ano,hora_ocorrido
0,1,ROUBO CONSUMADO,JAN,2012-01-01,DOMINGO,03:05:00,De 03:00 as 03:59,DIFICULDADE FINANCEIRA / COBICA,"INSTRUMENTO PERFURANTE, CORTANTE OU CONTUNDENTE",PREENCHIMENTO OPCIONAL,DISTRITO INDUSTRIAL,2012,03
1,1,ROUBO CONSUMADO,JAN,2012-01-01,DOMINGO,20:30:00,De 20:00 as 20:59,OUTROS - CAUSAS COMUNS,AGRESSAO FISICA,PREENCHIMENTO OPCIONAL,MUCUNGE DA GRAMA,2012,20
2,1,ROUBO CONSUMADO,JAN,2012-02-01,SEGUNDA-FEIRA,13:00:00,De 13:00 as 13:59,DIFICULDADE FINANCEIRA / COBICA,ARMAS DE FOGO,PREENCHIMENTO OPCIONAL,SAO BENEDITO,2012,13
3,1,ROUBO CONSUMADO,JAN,2012-02-01,SEGUNDA-FEIRA,18:00:00,De 18:00 as 18:59,OUTRAS MOTIVACOES/CAUSAS,OUTROS MEIOS (DESCREVER EM CAMPO ESPECIFICO),PREENCHIMENTO OPCIONAL,MARIANO PROCOPIO,2012,18
4,1,ROUBO CONSUMADO,JAN,2012-03-01,TERÇA-FEIRA,16:10:00,De 16:00 as 16:59,DIFICULDADE FINANCEIRA / COBICA,ARMAS DE FOGO,PREENCHIMENTO OPCIONAL,CENTRO,2012,16

In [84]:
# ´calculando o numero de ocorrencias por faixa horária
tabela['faixa_horaria_crime'].value_counts()

faixa_horaria_crime
De 21:00 as 21:59            1650
De 22:00 as 22:59            1578
De 20:00 as 20:59            1558
De 23:00 as 23:59            1349
De 19:00 as 19:59            1273
De 00:00 as 00:59            1173
De 18:00 as 18:59            1044
De 17:00 as 17:59             813
De 15:00 as 15:59             789
De 01:00 as 01:59             742
De 13:00 as 13:59             721
De 16:00 as 16:59             717
De 14:00 as 14:59             712
De 12:00 as 12:59             693
De 11:00 as 11:59             621
De 02:00 as 02:59             608
De 10:00 as 10:59             553
De 05:00 as 05:59             544
De 03:00 as 03:59             529
De 06:00 as 06:59             513
De 04:00 as 04:59             504
De 07:00 as 07:59             471
De 09:00 as 09:59             469
De 08:00 as 08:59             407
De 00:00 as 00:59              69
De 22:00 as 22:59              55
De 21:00 as 21:59              54
De 20:00 as 20:59              46
De 23:00 as 23:59              46
De 19:00 as 19:59              38
De 12:00 as 12:59              35
De 11:00 as 11:59              29
De 16:00 as 16:59              26
De 13:00 as 13:59              26
De 02:00 as 02:59              26
De 18:00 as 18:59              26
De 01:00 as 01:59              25
De 14:00 as 14:59              24
De 03:00 as 03:59              24
De 09:00 as 09:59              24
De 10:00 as 10:59              23
De 05:00 as 05:59              22
De 15:00 as 15:59              22
De 17:00 as 17:59              21
De 04:00 as 04:59              17
De 06:00 as 06:59              17
De 08:00 as 08:59              14
De 07:00 as 07:59              12
Name: count, dtype: int64

In [ ]:
# from geopy.geocoders import Nominatim
# import folium

# lista_bairros = tabela['bairro'].unique()
# lista_bairros



# for bairro in lista_bairros:
#     geolocalizador = Nominatim(user_agent='localizador')
#     localizador = geolocalizador.geocode(bairro)

#     mapa = folium.Map(location = [localizador.latitude, localizador.longitude], zoom_start=15)
#     folium.Marker(
#         [localizador.latitude, localizador.longitude],
#         popup=localizador.address,
#         tooltip="Clique para ver"
#     ).add_to(mapa)
# mapa